### ISSUE TITLE
Akord-js login error

### ISSUE THREAD

**Issue by tmicltw** [Akord-com/akord-cli#16]
Hi Weronika,

How's it going?

Let me share a report I got from TBN about a bug in Akord-js this morning:

"After logging in with akord-cli

akord vault:list

after logging in with akord-cli

Oops, something went wrong when loading your wallet: Error: Unsupported state or unable to authenticate data
Make sure that your keyfile is configured: akord wallet:configure --help

and I am not able to see the vault."

If more information is needed to fix this bug, please let me know!
Thanks,

**Comment by jarrvis** [comment]
This is fixed now.
Multiple accounts support was added together with improved exception handling, verbose logging both to console and to file.

In case of any issues please make sure to use up to date version of CLI.

**Comment by tehsunnliu** [comment]
Hi, I tried using the tag version `v1.0.19` and the main branch and I'm still getting this error even after logging in multiple times. 
<img width="381" alt="image" src="https://github.com/Akord-com/akord-cli/assets/15224865/755707de-d2c6-4a66-a967-1e99358d229e">

While installing Akord-cli using `yarn global add @akord/akord-cli` I get this warning.

<img width="739" alt="image" src="https://github.com/Akord-com/akord-cli/assets/15224865/bec2f6e5-6517-4d7a-8e36-abb09b5d9d78">

Not sure what's wrong. 
Thank you.

**Comment by jarrvis** [comment]
Hi @tehsunnliu,
looks like your akord wallet was not stored locally. This should normally happen after successful login: `akord login {username} {password}`. We are storing encrypted wallet in file on your local disk. Subsequent commands in CLI are reusing the encrypted wallet and so are dependent on `akord login` step.

It might be that the file was not created properly. Possible reason could be lack of permissions to touch the path.
Can you maybe check the contents of the following directory: ~/.akord
There you should find two files: logs and credentials. You can have a look at `logs` file (if exists) to find the reason why encrypted wallet (`credentials` file) is corrupted after login step
